version: '3.5'
services:
  # MongoDb
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
      
  # Backend
  redlake:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/redlake
    command: yarn start
    working_dir: /usr/src/redlake
    ports:
      - '8082:8082'
    links:
      - mongo
